// <auto-generated />
namespace LAB03_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Createcourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createcourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202106290301588_Createcourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
